# markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_blocks: false

# Inline HTML allowed
MD033: false

# First line heading not required
MD041: false
